# Generated by Django 3.1.7 on 2021-03-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('Asiel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerHomerPluginModel',
        ),
    ]
