# Generated by Django 3.1.7 on 2021-03-19 21:34

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('Asiel', '0003_bannerhomerpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhomerpluginmodel',
            name='imagen1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Imagen333'),
        ),
    ]
