# Generated by Django 3.1.7 on 2021-03-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('Asiel', '0005_auto_20210319_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerHomerPluginModel',
        ),
    ]
