# Generated by Django 3.1.7 on 2021-03-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiel', '0007_bannerhomerpluginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerhomerpluginmodel',
            old_name='cover',
            new_name='imagen2',
        ),
    ]
