# Generated by Django 3.1.7 on 2021-03-19 22:20

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('Asiel', '0008_auto_20210319_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerhomerpluginmodel',
            name='back',
        ),
        migrations.AddField(
            model_name='bannerhomerpluginmodel',
            name='imagen3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Imagen_3', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='bannerhomerpluginmodel',
            name='imagen2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Imagen_2', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
