# Generated by Django 3.1.7 on 2021-04-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('Asiel', '0011_homeseccionpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='asiel_aboutmepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('titulo', models.CharField(max_length=100)),
                ('biografa', models.CharField(max_length=10000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
