# Generated by Django 3.1.7 on 2021-04-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('Asiel', '0015_aboutmepluginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMePluginModel',
        ),
    ]
